### ISSUE TITLE
After the Yunohost migration to Denian 12 the daemon seem to not work

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/friendica_ynh#148]
I am posting it here too in case anyone can help. The original issue is here https://github.com/friendica/friendica/issues/14627

I have upgraded to server to Debian 12. I am using the Yunohost package for Friendica https://github.com/YunoHost-Apps/friendica_ynh . After the upgrade all seemed to work fine - I was getting new post updates from the people I followed even registrations requests. But a day later I realized this:

![image](https://github.com/user-attachments/assets/8a1cfb39-eea0-48b3-9b84-bef6aff07cf9)

`The last worker process started at 2024-12-24 22:58:07 UTC. This is more than one hour ago. Please adjust your crontab settings.`

The Friendica Yunohost uses a daemon and the daemon is working when I check the server's processes:

![image](https://github.com/user-attachments/assets/45940c9e-0da8-457d-8c87-a70a9b44adf8)

But when I SSH into the server and from Friendica's install folder I do "bin/daemon.php status" I get: `Friendica isn't properly installed yet`. It is the first time I see this. When I try to put Friendica in maintenance mode I get 
```
root@server /var/www/friendica # bin/console maintenance 1
[Error] Database isn't ready or populated yet
```

This is so strange....can anyone help? We've been running Friendica for a while now and it worked just fine. The Yunohost and Debian upgrade should not have touched the Friendica package.

From the daemon logs I see this https://paste.yunohost.org/ibujozamep and especially:
```

#8 /var/www/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#9 /var/www/friendica/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#10 /var/www/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#11 /var/www/friendica/bin/daemon.php(64): Dice\Dice->create()
#12 {main}
  thrown in /var/www/friendica/src/Database/Database.php on line 201
Starting worker daemon.
Child process started with pid 898204.
PHP Fatal error:  Uncaught mysqli_sql_exception: No such file or directory in /var/www/friendica/src/Database/Database.php:201
Stack trace:
#0 /var/www/friendica/src/Database/Database.php(201): mysqli->__construct()
#1 /var/www/friendica/src/Database/Database.php(106): Friendica\Database\Database->connect()
#2 [internal function]: Friendica\Database\Database->__construct()
#3 /var/www/friendica/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs()
#4 /var/www/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#5 /var/www/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#6 /var/www/friendica/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#7 /var/www/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#8 /var/www/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#9 /var/www/friendica/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#10 /var/www/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#11 /var/www/friendica/bin/daemon.php(64): Dice\Dice->create()
#12 {main}
  thrown in /var/www/friendica/src/Database/Database.php on line 201
Starting worker daemon.
Child process started with pid 963790.
Worker daemon process 963790 was killed.
Starting worker daemon.
Child process started with pid 2050.
Worker daemon process 2050 was killed.
Starting worker daemon.
Child process started with pid 1961.
Starting worker daemon.
Child process started with pid 2993.
Starting worker daemon.
Child process started with pid 3329.
Starting worker daemon.
Child process started with pid 2814.
Worker daemon process 2814 was killed.
Starting worker daemon.
Child process started with pid 2300.
Worker daemon process 2300 was killed.
Starting worker daemon.
Child process started with pid 2142.
Worker daemon process 2142 was killed.
Starting worker daemon.
Child process started with pid 2028.
Worker daemon process 2028 was killed.
Starting worker daemon.
Child process started with pid 14988.
```

`Uncaught mysqli_sql_exception: No such file or directory in /var/www/friendica/src/Database/Database.php:201` ???

**Comment by tio-trom** [comment]
Update: I found out that running `sudo -u friendica /usr/bin/php8.2 /var/www/friendica/bin/worker.php` can run the worker and fix the issue. But I am wondering how to fix this for good. The systemd file is this:

```
[Unit]
Description=Friendica daemon
After=network.target mariadb.service
Requires=network.target remote-fs.target nss-lookup.target

[Service]
User=friendica
Group=www-data
WorkingDirectory=/var/www/friendica/
Type=simple
StandardOutput=append:/var/log/friendica/daemon.log
StandardError=inherit
ExecStart=/usr/bin/php8.2 /var/www/friendica/bin/daemon.php start
ExecStop=/usr/bin/php8.2 /var/www/friendica/bin/daemon.php stop
PIDFile=/var/www/friendica/daemon.pid
PrivateTmp=true
InaccessibleDirectories=/home /root /boot /opt /mnt /media
ReadOnlyDirectories=/etc /usr
Restart=always
RestartSec=10
StartLimitBurst=1

# Sandboxing options to harden security
# Depending on specificities of your service/app, you may need to tweak these 
# .. but this should be a good baseline
# Details for these options: https://www.freedesktop.org/software/systemd/man/systemd.exec.html
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
RestrictNamespaces=yes
RestrictRealtime=yes
DevicePolicy=closed
ProtectClock=yes
ProtectHostname=yes
ProtectProc=invisible
ProtectSystem=full
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
LockPersonality=yes
SystemCallArchitectures=native
SystemCallFilter=~@clock @debug @module @mount @obsolete @reboot @setuid @swap @cpu-emulation @privileged

# Denying access to capabilities that should not be relevant for webapps
# Doc: https://man7.org/linux/man-pages/man7/capabilities.7.html
CapabilityBoundingSet=~CAP_RAWIO CAP_MKNOD
CapabilityBoundingSet=~CAP_AUDIT_CONTROL CAP_AUDIT_READ CAP_AUDIT_WRITE
CapabilityBoundingSet=~CAP_SYS_BOOT CAP_SYS_TIME CAP_SYS_MODULE CAP_SYS_PACCT
CapabilityBoundingSet=~CAP_LEASE CAP_LINUX_IMMUTABLE CAP_IPC_LOCK
CapabilityBoundingSet=~CAP_BLOCK_SUSPEND CAP_WAKE_ALARM
CapabilityBoundingSet=~CAP_SYS_TTY_CONFIG
CapabilityBoundingSet=~CAP_MAC_ADMIN CAP_MAC_OVERRIDE
CapabilityBoundingSet=~CAP_NET_ADMIN CAP_NET_BROADCAST CAP_NET_RAW
CapabilityBoundingSet=~CAP_SYS_ADMIN CAP_SYS_PTRACE CAP_SYSLOG 

[Install]
WantedBy=multi-user.target
```

**Comment by tio-trom** [comment]
This is the fix https://github.com/friendica/friendica/issues/14627#issuecomment-2562954670
