### ISSUE TITLE
Impossible to reset user password

### ISSUE THREAD

**Issue by autra** [YunoHost-Apps/friendica_ynh#21]
The app fails when I try to reset my password.

# steps

Use the "reset password" link, and click on the link received by mail.

After a while, the page stops loading (still blank) and I have these logs with `yunohost service log php7.0-fpm`:

```
- [16-Dec-2019 21:03:24] WARNING: [pool friendica] child 6153, script '/var/www/friendica//index.php' (request: "GET /index.php?pagename=/lostpass/grartaubaixe1731") executing too slow (5.349857 sec), logging
  - [16-Dec-2019 21:03:24] NOTICE: child 6153 stopped for tracing
  - [16-Dec-2019 21:03:24] NOTICE: about to trace 6153
  - [16-Dec-2019 21:03:24] NOTICE: finished trace of 6153
  - [16-Dec-2019 21:03:25] WARNING: [pool friendica] child 6153 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught ParagonIE\Certainty\Exception\BundleException: No valid bundles were found in the data directory. in /var/www/friendica/vendor/paragonie/certainty/src/Fetch.php:85"
  - [16-Dec-2019 21:03:25] WARNING: [pool friendica] child 6153 said into stderr: "Stack trace:"
  - [16-Dec-2019 21:03:25] WARNING: [pool friendica] child 6153 said into stderr: "#0 /var/www/friendica/vendor/divineomega/password_exposed/src/PasswordExposedChecker.php(72): ParagonIE\Certainty\Fetch->getLatestBundle()"
  - [16-Dec-2019 21:03:25] WARNING: [pool friendica] child 6153 said into stderr: "#1 /var/www/friendica/vendor/divineomega/password_exposed/src/PasswordExposedChecker.php(45): DivineOmega\PasswordExposed\PasswordExposedChecker->getBundleFromCertainty()"
  - [16-Dec-2019 21:03:25] WARNING: [pool friendica] child 6153 said into stderr: "#2 /var/www/friendica/src/Model/User.php(299): DivineOmega\PasswordExposed\PasswordExposedChecker->__construct(Object(GuzzleHttp\Client), Object(DivineOmega\DOFileCachePSR6\CacheItemPool))"
  - [16-Dec-2019 21:03:25] WARNING: [pool friendica] child 6153 said into stderr: "#3 /var/www/friendica/src/Model/User.php(347): Friendica\Model\User::isPasswordExposed('Glalfeat8751')"
  - [16-Dec-2019 21:03:25] WARNING: [pool friendica] child 6153 said into stderr: "#4 /var/www/friendica/mod/lostpass.php(133): Friendica\Model\User::updatePassword(2, 'Glalfeat8751')"
  - [16-Dec-2019 21:03:25] WARNING: [pool friendica] child 6153 said into stderr: "#5 /var/www/friendica/mod/lostpass.php(108): lostpass_generate_password(Array)"
  - [16-Dec-2019 21:03:25] WARNING: [pool friendica] child 6153 said into stderr: "#6 /var/www/f..."

```

Please let me know if I can provide more info.

**Comment by tobiasd** [comment]
To bypass the problem you can disable the check if the new password was included of an exposed password collection by setting `disable_password_exposed` in your configuration file to `true`. At the moment this setting is _**not**_ available in the admin panel.

See friendica/friendica#7796 for a more detailed discussion. This problem should be fixed in Friendica 2019.12

**Comment by anmol26s** [comment]
@tobiasd Is the issue resolved in the 2020.03 ?

**Comment by tobiasd** [comment]
It _should be_ ;) I've not tested it TBH

**Comment by anmol26s** [comment]
@anmol26s Thanks
