### ISSUE TITLE
No way to upload  a profile photo (jpg)

### ISSUE THREAD

**Issue by Shnoulle** [YunoHost-Apps/friendica_ynh#86]
### Describe the bug

Ater 1st login, try to upload a jpg file for profile
Get an error

```
Exception produite dans /var/www/friendica/src/Module/Settings/Profile/Photo/Crop.php:175
Stack trace:
#0 /var/www/friendica/src/BaseModule.php(239): Friendica\Module\Settings\Profile\Photo\Crop->content()
#1 /var/www/friendica/src/App.php(712): Friendica\BaseModule->run()
#2 /var/www/friendica/index.php(44): Friendica\App->runFrontend()
#3 {main}
```

### Context

- Hardware: *Old omputer.*
- YunoHost version: 11.0.10.1
- I have access to my server: *Through SSH && through the webadmin && direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: Friendica 2022.06~ynh1

### Steps to reproduce

After log in
Edit profile
Click on top : add a photo to profile
Select a jpg file
Upload
Receive error

### Expected behavior

Show crop system

**Comment by Shnoulle** [comment]
Fixed by 
`apt install php-gd`
